### ISSUE TITLE
Reading RAW data from GPSD

### ISSUE THREAD

**Issue by Rutger798** [eeeeeta/unbounded-gpsd#2]
He, 

I need to read RAW data from the GPSD to check the GPS status and the status of the connected OSXO.

I fork your repository to extend your watch interface with the following parameters:
fn watch(&mut self, watch: bool, json: bool, raw: u8)

And I will make the get_response function cable of returning raw data.

Are you willing to merge this in the near future or do I need to make this possible in some other way?

**Comment by eeeeeta** [comment]
Fixed in #3.
